# Generated by Django 3.0.8 on 2020-08-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Desginer',
            new_name='Designer',
        ),
    ]
